#github action deployment file
name: deploy
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Authenticate to google
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GC_SERVICE_ACCOUNT_KEY }}
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GC_PROJECT }}
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      # INIT AND APPLY TERRAFORM STATE
      - name: terraform init state
        run: terraform -chdir=path/to/terraform/state init -input=false

      - name: terraform apply state
        run: terraform -chdir=path/to/terraform/state apply -input=false -auto-approve

      # INIT AND APPLY INFRASTRUCTURE
      - name: terraform init infrastructure
        run: terraform -chdir=path/to/terraform/ init -migrate-state -input=false

      - name: terraform apply infrastructure
        run: terraform -chdir=path/to/terraform/ apply -input=false -auto-approve
